name: C - Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows x86_64

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make -c 3_Implementation/ all

