name: C/C++ CI -Build status

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make -C 3_Implemenetation/ all
